export const siteConfig = {
  name: "Nehil Chandrakar",
  tagline: "Born builder — crafting systems, shaping experiences.",
  role: "Builder • Engineer • Designer",
  contact: {
    email: "chnadrakarnehil.06112002@gmail.com",
    phone: "+919131203322",
    location: "Tumkur, India",
  },
  socials: {
    linkedin: "https://www.linkedin.com/in/nehil-chandrakar-272410259/",
    x: "https://x.com/Chandrakar43234",
    github: "https://github.com/NEhIL06",
    leetcode: "https://leetcode.com/u/Nehil_chandrakar/",
  },
  education: {
    institute: "Siddaganga Institute of Technology",
    location: "Tumkur, India",
    degree: "B.E. in CSE (AI/ML)",
    graduation: "Jun 2026",
  },
  skills: {
    languages: ["Java", "JavaScript", "Python"],
    frameworks: [
      "Spring Boot",
      "React.js",
      "Node.js",
      "Express.js",
      "React Native",
      "AWS (Lambda, SageMaker)",
      "Git",
      "Docker",
      "MongoDB",
      "MySQL",
      "Redis",
    ],
    fundamentals: [
      "Database Management",
      "Data Structures & Algorithms",
      "Operating Systems",
      "Object-Oriented Programming",
    ],
  },
  projectsPage: {
    title: "Selected Projects",
    quote: "I build systems that look simple on the surface and remain dependable under pressure.",
  },
  projects: [
    // Provided additions
    {
      title: "KeyBank",
      description: "AI-enabled API key management to store, rotate, and retrieve keys securely.",
      stack: ["Next.js", "TypeScript", "PostgreSQL", "tRPC", "JWT"],
      link: "#",
      demo: undefined,
      image: "/placeholder.svg?height=720&width=1280",
      facts: ["Secret versioning & rotation", "AI suggestions for least-privilege policies", "Audit trails"],
    },
    {
      title: "The Journal (Frontend)",
      description: "Minimal Next.js front-end for a journaling platform focused on clarity and calm UI.",
      stack: ["Next.js", "React", "Tailwind CSS"],
      link: "#",
      demo: undefined,
      image: "/placeholder.svg?height=720&width=1280",
      facts: ["Keyboard-first interactions", "Local drafts & autosave", "Theming and accessibility"],
    },
    {
      title: "NewsAnchor",
      description: "An AI-powered news anchor that summarizes, narrates, and presents daily headlines.",
      stack: ["Next.js", "Node.js", "TTS", "LLM"],
      link: "#",
      demo: undefined,
      image: "/placeholder.svg?height=720&width=1280",
      facts: ["Multi-lingual narration", "Topic clustering", "Daily digest pipeline"],
    },
    {
      title: "InstaFood",
      description: "Instant food delivery experience with streamlined browsing and checkout.",
      stack: ["React Native", "Node.js", "Stripe", "Redis"],
      link: "#",
      demo: undefined,
      image: "/placeholder.svg?height=720&width=1280",
      facts: ["Real-time delivery tracking", "Optimized menus & search", "Offer scheduling"],
    },
    {
      title: "AWS Music Recommender",
      description: "AI-based music recommender backed by AWS services.",
      stack: ["AWS", "Python", "SageMaker", "Lambda"],
      link: "#",
      demo: undefined,
      image: "/placeholder.svg?height=720&width=1280",
      facts: ["Feature stores on AWS", "Hybrid recommenders", "A/B tested playlists"],
    },
    {
      title: "WebGen",
      description: "AI-powered website generator that scaffolds modern, responsive sites.",
      stack: ["Next.js", "LLM", "Tailwind CSS"],
      link: "#",
      demo: undefined,
      image: "/placeholder.svg?height=720&width=1280",
      facts: ["Component library aware generation", "Prompt presets", "One-click export"],
    },
    {
      title: "AI Photo Editor",
      description: "Photo editor with AI-based transformations and retouching.",
      stack: ["React", "WebGL", "LLM", "Cloud Functions"],
      link: "#",
      demo: undefined,
      image: "/placeholder.svg?height=720&width=1280",
      facts: ["Inpainting / background removal", "Look presets", "Batch operations"],
    },

    // Previously included
    {
      title: "Krishi Baazar",
      description: "Mobile app empowering small farmers to list crops and connect directly with buyers.",
      stack: ["React Native", "Appwrite", "Node.js", "Redis", "REST APIs"],
      link: "#",
      demo: undefined,
      image: "/placeholder.svg?height=720&width=1280",
      facts: [
        "Real-time weather and market news inside the app",
        "Appwrite auth/storage/notifications",
        "Redis caching boosted API performance",
      ],
    },
    {
      title: "Avanti",
      description: "AI assistant simplifying travel ticketing and banking for elderly & multilingual users.",
      stack: ["Three.js", "React.js", "Node.js", "Flask", "Gemini", "11Labs", "Rhubarb", "ffmpeg", "Sarvam.ai"],
      link: "#",
      demo: undefined,
      image: "/placeholder.svg?height=720&width=1280",
      facts: [
        "Interactive avatar with lip-sync",
        "Bridges language gaps",
        "Speech recognition + TTS + Flask NLP",
      ],
    },
    {
      title: "SkyScope",
      description: "Backend for a real-time 2D virtual office enabling presence and collaboration.",
      stack: ["TurboRepo", "Node.js", "WebSockets", "WebRTC", "MongoDB", "Redis", "Docker", "CI/CD"],
      link: "#",
      demo: undefined,
      image: "/placeholder.svg?height=720&width=1280",
      facts: [
        "Proximity-based P2P voice chat",
        "Public chat with MongoDB persistence",
        "TDD, containers, CI/CD",
      ],
    },
  ],
  achievements: [
    { title: "Mercuria India Hackathon 2024 — EcoSap", subtitle: "2nd Prize", date: "Nov 2024" },
    { title: "Emerging Tech Hackathon 2024 — Multi-Agent Orchestration for Choice Prediction", subtitle: "Honourable Mention", date: "Dec 2024" },
    { title: "The Better Hack 2025 — Jarvis for Food (Multi-agentic orchestration using GRPO)", subtitle: "Top 5", date: "May 2025" },
    { title: "LinkedIn", subtitle: "500+ Connections", date: "May 2025" },
  ],
  clubs: [
    {
      name: "AI BREWERY",
      role: "Founding Member",
      since: "Nov 2024 – Present",
      location: "SIT, KA",
      posts: ["Co-founded an organization empowering students in emerging tech."],
    },
    {
      name: "SARK",
      role: "Member",
      since: "Dec 2022 – Present",
      location: "SIT, KA",
      posts: ["Conducted workshops teaching 350+ students."],
    },
  ],
  about: {
    intro:
      "Beyond building systems, I explore design, communities, and learning in public. I love hackathons, photography, and sharing knowledge through video.",
    hobbies: [
      {
        title: "Design + Aesthetics",
        description: "Exploring minimal, functional design that feels premium.",
        image: "/placeholder.svg?height=900&width=1600",
      },
      {
        title: "Hackathons",
        description: "Rapidly prototyping ideas with a bias for shipping.",
        image: "/placeholder.svg?height=900&width=1600",
      },
      {
        title: "Photography",
        description: "Capturing stories in light and contrast.",
        image: "/placeholder.svg?height=900&width=1600",
      },
    ],
    gallery: [
      { src: "/placeholder.svg?height=1200&width=1600", caption: "EcoSap — 2nd Prize, Mercuria 2024" },
      { src: "/placeholder.svg?height=1200&width=1600", caption: "Late-night sprint with the team" },
      { src: "/placeholder.svg?height=1200&width=1600", caption: "Hands-on workshop at SARK" },
      { src: "/placeholder.svg?height=1200&width=1600", caption: "Project demo booth" },
      { src: "/placeholder.svg?height=1200&width=1600", caption: "Conversations and connections" },
    ],
    youtube: {
      channelName: "Your Channel Name",
      tagline: "Engineering, design, and shipping better software.",
      link: "https://www.youtube.com/@your-channel",
      latestVideo: "https://www.youtube.com/watch?v=example",
      preview: "/placeholder.svg?height=720&width=1280",
    },
  },
}
